{% set version = "2.10.0" %}
{% set python_min = "3.11" %}

package:
  name: mapclassify
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mapclassify/mapclassify-{{ version }}.tar.gz
  sha256: 0d6736a08c0b1e10e6197224ef512951514204706514244bd01aea49fd1442b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - scipy >=1.8
    - numpy >=1.23
    - scikit-learn >=1.0
    - pandas >=1.4,!=1.5.0
    - networkx >=2.7

test:
  imports:
    - mapclassify
    - mapclassify.datasets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pysal/mapclassify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  dev_url: https://github.com/pysal/mapclassify

extra:
  recipe-maintainers:
    - jGaboardi
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
    - martinfleis
    - knaaptime
