{% set version = "2.0.0" %}

package:
  name: mapclassify
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mapclassify/mapclassify-{{ version }}.tar.gz
  sha256: 66c932eb41675bf9608f86377c6e3f6bd4d96180400440688c743f00d623bb4e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - pandas
    - scipy

test:
  imports:
    - mapclassify
    - mapclassify.datasets
    - mapclassify.datasets.calemp

about:
  home: https://github.com/pysal/mapclassify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  dev_url: https://github.com/pysal/mapclassify

extra:
  recipe-maintainers:
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
