{% set version = "23.1" %}

package:
  name: mapclassify
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mapclassify/mapclassify-{{ version }}.tar.gz
  sha256: 146c4e48f6944fb1214c9bafe39c3c4ce1dd54ff705cac14ca200f25d4455d34

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy >=1.0
    - numpy >=1.3
    - scikit-learn
    - pandas >=1.0
    - networkx

test:
  imports:
    - mapclassify
    - mapclassify.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/mapclassify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  dev_url: https://github.com/pysal/mapclassify

extra:
  recipe-maintainers:
    - jGaboardi
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
