{% set version = "1.0.1" %}

package:
  name: mapclassify
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mapclassify/mapclassify-{{ version }}.tar.gz
  sha256: a905be0f124a8d0b96fd9a65c65afcc9699a07e25dc3a3ac445e51e2df380ec7

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - scipy

test:
  imports:
    - mapclassify
    - mapclassify.datasets
    - mapclassify.datasets.calemp

about:
  home: https://github.com/pysal/mapclassify
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: Classification schemes for choropleth maps
  dev_url: https://github.com/pysal/mapclassify

extra:
  recipe-maintainers:
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
